// src/components/SwatchPallete/Swatch.tsx
import React, { ReactElement } from 'react';
import { UICOLOURS } from '../../types';
import * as S from '../../stateCode';
import styled from 'styled-components';
import { hcl } from 'd3';
const SButton = styled.button`
  height: 4em;
  width: 4em;
  font-size: inherit;
  margin: 0.2em;
  border-width: 0.25em;
  border-style: solid;
  border-color: var(--border);
  border-radius: 1em;
  background-color: var(--fill);
  transform: scale(1);
  transition: transform 233ms, border-width 233ms;
  cursor: pointer;

  &:hover {
    transform: scale(1.125);
  }
  &:focus {
    outline: none;
  }
`;

interface Props {
  location: [number, number];
  color: S.Colour;
  selected: boolean;
  selector: (toSelect: [number, number]) => any;
}

export function Swatch({ color, selected, location, selector }: Props): ReactElement {
  const svgProps = {
    viewbox: '0 0 1 1',
  };
  const css: React.CSSProperties = {
    borderWidth: selected ? '0.5em' : '0.25em',
  };

  return (
    <SButton
      style={
        {
          '--fill': color.hex,
          '--border': color.light ? UICOLOURS.DARK_COL : UICOLOURS.LIGHT_COL,
          ...css,
        } as any
      }
      onClick={() => {
        if (selected) selector([-1, -1]);
        else selector(location);
      }}
    />
  );
}
export default Swatch;

// src/components/Pallete/Swatch.svelte
<script lang="ts">
  import * as s from '../../stateCode';
  import * as d3 from 'd3';
  export let col = '#ef3355';
  $: brdr_col = d3.hcl(col).l > 50 ? '#303030' : '#e0e0e0';
  $: hvr_col = brdr_col + '60';
  export let sel = Math.random() < 0.5;
</script>

<button
  class:sel
  style="--swatch-col: {col};--brdr-col: {brdr_col}; --hvr-col: {hvr_col}"
/>

<style>
  button {
    width: 5em;
    height: 5em;
    margin: 0;
    border: 0;
    padding: 0.2em;
    background-color: var(--swatch-col);
    cursor: pointer;
    transition: all 50ms;
  }
  button:hover {
    border: 0.3em solid var(--hvr-col);
  }
  button.sel {
    border: 0.4em solid var(--brdr-col);
  }
  button.sel:hover {
    border: 0.4em solid var(--hvr-col);
  }

  button:focus {
    border: 0.3em solid var(--hvr-col);
    outline: 0;
  }
</style>
